package com.king.bio.common.model;

import com.king.bio.common.model.base.BaseBioFavorites;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BioFavorites extends BaseBioFavorites<BioFavorites> {
	public static final BioFavorites dao = new BioFavorites().dao();
}
