package com.king.bio.common.model;

import com.king.bio.common.model.base.BaseBioFeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BioFeedback extends BaseBioFeedback<BioFeedback> {
	public static final BioFeedback dao = new BioFeedback().dao();
}
