package com.king.bio.common.model;

import com.king.bio.common.model.base.BaseBioUserImg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BioUserImg extends BaseBioUserImg<BioUserImg> {
	public static final BioUserImg dao = new BioUserImg().dao();
}
