package com.king.bio.common.model;

import com.king.bio.common.model.base.BaseBioUserShare;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BioUserShare extends BaseBioUserShare<BioUserShare> {
	public static final BioUserShare dao = new BioUserShare().dao();
}
