package com.king.bio.common.model;

import com.king.bio.common.model.base.BaseBioUserInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BioUserInfo extends BaseBioUserInfo<BioUserInfo> {
	public static final BioUserInfo dao = new BioUserInfo().dao();
}
