package com.king.bio.common.model;

import com.king.bio.common.model.base.BaseSysRoleMoudle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleMoudle extends BaseSysRoleMoudle<SysRoleMoudle> {
	public static final SysRoleMoudle dao = new SysRoleMoudle().dao();
}
