package com.king.bio.common.model;

import com.king.bio.common.model.base.BaseSysRoleUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleUser extends BaseSysRoleUser<SysRoleUser> {
	public static final SysRoleUser dao = new SysRoleUser().dao();
}
