package com.king.bio.common.model;

import com.king.bio.common.model.base.BaseSysUserInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUserInfo extends BaseSysUserInfo<SysUserInfo> {
	public static final SysUserInfo dao = new SysUserInfo().dao();
}
