package com.king.bio.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysUserInfo<M extends BaseSysUserInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public M setRealname(java.lang.String realname) {
		set("realname", realname);
		return (M)this;
	}

	public java.lang.String getRealname() {
		return get("realname");
	}

	public M setPwd(java.lang.String pwd) {
		set("pwd", pwd);
		return (M)this;
	}

	public java.lang.String getPwd() {
		return get("pwd");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public M setQq(java.lang.String qq) {
		set("qq", qq);
		return (M)this;
	}

	public java.lang.String getQq() {
		return get("qq");
	}

	public M setTel(java.lang.String tel) {
		set("tel", tel);
		return (M)this;
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public M setMemo(java.lang.String memo) {
		set("memo", memo);
		return (M)this;
	}

	public java.lang.String getMemo() {
		return get("memo");
	}

	public M setInuse(java.lang.Integer inuse) {
		set("inuse", inuse);
		return (M)this;
	}

	public java.lang.Integer getInuse() {
		return get("inuse");
	}

	public M setTag(java.lang.String tag) {
		set("tag", tag);
		return (M)this;
	}

	public java.lang.String getTag() {
		return get("tag");
	}

	public M setIsSystem(java.lang.Boolean isSystem) {
		set("is_system", isSystem);
		return (M)this;
	}

	public java.lang.Boolean getIsSystem() {
		return get("is_system");
	}

	public M setParentId(java.lang.Long parentId) {
		set("parent_id", parentId);
		return (M)this;
	}

	public java.lang.Long getParentId() {
		return get("parent_id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
		return (M)this;
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
